In [ ]:
# Numpy Activities

In [2]:
import numpy as np

# Creating and Saving NumPy ndarrays

# 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

print('x = ', x)



x =  [1 2 3 4 5]


In [4]:
#  x 4 ndarray full of zeros
x = np.zeros((3,4))

print()
print('x = \n', x)
print()

#Information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

x has dimensions: (3, 4)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [11]:
# Accesing Into ndarrays

# Rank 1 ndarray that contains integers from 1 to 5
x =np.array([1, 2, 3, 4, 5])

print()
print('x = ',x)
print()

# Access some elememnt with positive indices
print('This is first element in x:', x[0])
print('This is second element in x:', x[1])
print('This is firth (last) element in x:', x[4])
print()

# Access same elemnts with negative indices
print('This is first element in x:', x[-5])
print('This is second element in x:', x[-4])
print('This is fith (last) element in x:', x[-1])


x =  [1 2 3 4 5]

This is first element in x: 1
This is second element in x: 2
This is firth (last) element in x: 5

This is first element in x: 1
This is second element in x: 2
This is fith (last) element in x: 5


In [10]:
# Slicing ndarrays

# 4 x 5 ndarray that contains integers from 0 to 19
x = np.arange(20).reshape(4, 5)

print()
print('x = \n', x)
print()

# Select all the elements that are in the 2nd through 4th and in the 3rd to 5th columns
# (The 1st being index 0)
Z = x[1:4,2:5]

print('Z = \n', Z)

# Select the same elements as above using method 2
w = x[1:,2:5]

print()
print('w = \n', w)

# Select all the elements that are in 1st through 3rd rows and in the  3rd to 4th columns
y = x[:3,2:5]

print()
print('y = \n', y)

# Select all the elemnts in the 3rd column
q = x[:,2]

print()
print('q = ', q)

# Select all the elemnts in the 3rd column but return a rank 2 ndarray
r = x[:,2:3]

print()
print('r = \n', r)




x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

w = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

q =  [ 2  7 12 17]

r = 
 [[ 2]
 [ 7]
 [12]
 [17]]


In [14]:
# Boolean Indexing

# Create a 5 x 5 ndarray that contains integers from 0 to 24
x = np.arange(25).reshape(5, 5)

print()
print('Original x = \n', x)
print()

# Use Boolean indexing to select elemnts in x:
print('The elements in x that are greater than 10:', x[x > 10])
print('The elements in x that less than or equal to 7:', x[x <= 7])
print('The elements in x that are between 10 and 17:', x[(x > 10) & (x < 17)])

# Use Boolean indexing to assign the elemnts that are between 10 and 17 the value of -1
x[(x > 10) & (x < 17)] = -1

print()
print('x = \n', x)
print()


Original x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in x that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in x that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in x that are between 10 and 17: [11 12 13 14 15 16]

x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



In [18]:
# Set operations

# Create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# Create a rank 1 ndarray
y = np.array([6,7,2,8,4])

print()
print('x = ', x)

print()
print('y = ', y)

# Use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elemnts that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elemnts of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elemnts that are in x that are not in y: [1 3 5]
All the elemnts of x and y: [1 2 3 4 5 6 7 8]


In [20]:
# Arithmetic Operations

# Create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

print()
print('x = ', x)

print()
print('x = ', x)

print()
print('y = ', y)
print()

# Basic elemt_wise operations using arithmetics symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x *y = ', x - y)
print('subtract(x,y) = ',np.subtract(x,y))
print()
print('x *y = ', x* y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))


x =  [1 2 3 4]

x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x *y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x *y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]
